dubbo:
  registry:
    address: zookeeper://myhost:2181
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    port: 20880  # -1 : random port
    name: dubbo
  scan:
    base-packages: com.ab.demo.service
  application:
    name: dubbo-provider
